"""
Interactive first-time setup for Brand Content Agent.
Saves credentials to ~/.config/brand-content-agent/.env — outside the skill
directory so they survive reinstalls and skill updates.

Usage: uv run scripts/setup.py
"""

import getpass
import os
import stat
import sys
from pathlib import Path

CONFIG_DIR = Path.home() / ".config" / "brand-content-agent"
ENV_FILE = CONFIG_DIR / ".env"


def prompt(label: str, default: str = "", secret: bool = False) -> str:
    display = f"  {label}" + (f" [{default}]" if default else "") + ": "
    if secret:
        value = getpass.getpass(display)
    else:
        value = input(display).strip()
    return value or default


def main():
    print()
    print("╔══════════════════════════════════════════════╗")
    print("║     Brand Content Agent — Setup              ║")
    print("╚══════════════════════════════════════════════╝")
    print(f"\nCredentials will be saved to: {ENV_FILE}\n")

    if ENV_FILE.exists():
        print(f"  ⚠  Existing config found at {ENV_FILE}")
        overwrite = input("  Overwrite? [y/N]: ").strip().lower()
        if overwrite != "y":
            print("\nSetup cancelled. Existing config unchanged.\n")
            sys.exit(0)
        print()

    print("── Scalekit  (Dashboard → Developers → API Credentials) ──────────\n")
    scalekit_url = prompt("Scalekit environment URL", "https://your-env.scalekit.cloud")
    scalekit_id = prompt("Client ID (skc_...)")
    scalekit_secret = prompt("Client Secret (sks_...)", secret=True)

    print("\n── Apify  (apify.com → Settings → Integrations) ───────────────────\n")
    apify_token = prompt("Apify Token (apify_api_...)", secret=True)

    print("\n── Notion database IDs  (from each database page URL) ─────────────")
    print("   Press Enter to skip any you haven't created yet.\n")
    notion_content = prompt("Content Library DB ID")
    notion_scripts = prompt("Scripts DB ID")
    notion_creators = prompt("Creators DB ID")
    notion_calendar = prompt("Calendar DB ID")

    print("\n── Connection names  (press Enter to keep defaults) ────────────────\n")
    apify_conn = prompt("Apify connection name", "apifymcp")
    notion_conn = prompt("Notion connection name", "notion")
    gmail_conn = prompt("Gmail connection name", "gmail")
    user_id = prompt("User identifier", "user_123")

    env_content = "\n".join([
        "# Brand Content Agent — generated by setup.py",
        f"# {ENV_FILE}",
        "",
        "# Scalekit (https://docs.scalekit.com/agentkit/quickstart/)",
        f"SCALEKIT_ENV_URL={scalekit_url}",
        f"SCALEKIT_CLIENT_ID={scalekit_id}",
        f"SCALEKIT_CLIENT_SECRET={scalekit_secret}",
        "",
        "# Apify",
        f"APIFY_TOKEN={apify_token}",
        "",
        "# Connection names — must match Dashboard → AgentKit → Connections",
        f"APIFY_CONNECTION_NAME={apify_conn}",
        f"NOTION_CONNECTION_NAME={notion_conn}",
        f"GMAIL_CONNECTION_NAME={gmail_conn}",
        "",
        "# User identifier (any stable string that identifies this user)",
        f"USER_IDENTIFIER={user_id}",
        "",
        "# Notion database IDs",
        f"NOTION_DB_CONTENT_LIBRARY={notion_content}",
        f"NOTION_DB_SCRIPTS={notion_scripts}",
        f"NOTION_DB_CREATORS={notion_creators}",
        f"NOTION_DB_CALENDAR={notion_calendar}",
        "",
        "# Suppress noisy gRPC warnings on macOS",
        "GRPC_VERBOSITY=ERROR",
        "",
    ])

    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    ENV_FILE.write_text(env_content)
    ENV_FILE.chmod(stat.S_IRUSR | stat.S_IWUSR)  # 600 — owner read/write only

    print()
    print(f"  ✓  Saved to {ENV_FILE}")
    print("  ✓  Permissions set to owner-only (600)")
    print()
    print("Next step: authorize Notion + Gmail connections")
    print("  uv run scripts/ensure_connections.py")
    print()


if __name__ == "__main__":
    main()
